Updating instructions on dev docs and moving Make targets
CDCgov/multisignal-epi-inference pull request #264
Opened 2024-07-11 23:00 UTC by gvegayon

- Updates the instructions under `docs/source/developer_documentation.rst` reflecting where the tutorials live now.
- Moves all the `Makefile` targets under `./model/Makefile` to `./docs/Makefile`.

2024-07-12 16:37 UTC, dylanhmorris reviewed
One key question @gvegayon

2024-07-12 16:37 UTC, dylanhmorris commented on docs/source/tutorials/Makefile
Should this be its own thing or should it be part of `docs/Makefile`? As written, `docs/Makefile` seems to have commands that do nothing, and I think we should avoid recursive make where possible.

2024-07-15 20:39 UTC, dylanhmorris commented on docs/source/tutorials/Makefile
@gvegayon flagging this

2024-07-17 15:08 UTC, gvegayon commented on docs/source/tutorials/Makefile
The `docs/Makefile` was originally added with the Sphinx website. I tried to add the targets to build the qmd files, but that broke the Sphinx pipeline. The lines adding print info to `make help` are residual from that attempt. I've corrected that. The `docs/source/tutorials/Makefile` is a helper that contains targets to render and convert the qmd files to py and ipynb. Is the same file that used to live under `model/docs/`.

2024-07-17 19:05 UTC, dylanhmorris requested changes
@gvegayon one suggestion

2024-07-17 19:05 UTC, dylanhmorris commented on docs/source/tutorials/Makefile
In that case I suggest renaming the `.PHONY` targets from `docs_*` to `tutorials_*` for clarity.

2024-07-17 21:28 UTC, dylanhmorris commented
@gvegayon looks like this needs a pre-commit fix but then should be ready for re-review?

2024-07-18 02:13 UTC, dylanhmorris approved these changes

2024-07-18 03:18 UTC, merged